---
- name: "Fix /var/www/html/alma8-install folder permissions"
  hosts: management
  remote_user: root
  tasks:
    - name: put megaraid_sas driver in place
      copy: 
        src: /root/dd-megaraid_sas-07.717.02.00-1.el8_5.elrepo.iso
        dest: /var/www/html/alma8-install/dd-megaraid_sas-07.717.02.00-1.el8_5.elrepo.iso
        remote_src: yes
    - name: put mlx4 driver in place
      copy: 
        src: /root/dd-mlx4-4.0-6.el8_5.elrepo.iso
        dest: /var/www/html/alma8-install/dd-mlx4-4.0-6.el8_5.elrepo.iso
        remote_src: yes
    - name: "Fix alma8 permissions"
      file:
        path: /var/www/html/alma8-install/
        state: directory
        recurse: yes
        mode: '755'
...
