
.TH FENCE_AGENT 8 2009-10-20 "fence_kdump (Fence Agent)"
.SH NAME
fence_kdump - fencing agent for use with kdump crash recovery service
.SH DESCRIPTION
.P
\fIfence_kdump\fP is an I/O fencing agent to be used with the kdump
crash recovery service. When the \fIfence_kdump\fP agent is invoked,
it will listen for a message from the failed node that acknowledges
that the failed node it executing the kdump crash kernel.
Note that \fIfence_kdump\fP is not a replacement for traditional
fencing methods. The \fIfence_kdump\fP agent can only detect that a
node has entered the kdump crash recovery service. This allows the
kdump crash recovery service complete without being preempted by
traditional power fencing methods.

Note: the "off" action listen for message from failed node that
acknowledges node has entered kdump crash recovery service. If a valid
message is received from the failed node, the node is considered to be
fenced and the agent returns success. Failure to receive a valid
message from the failed node in the given timeout period results in
fencing failure.
.P
fence_kdump accepts options on the command line as well
as from stdin. Fenced sends parameters through stdin when it execs the
agent. fence_kdump can be run by itself with command
line options.  This is useful for testing and for turning outlets on or off
from scripts.

Vendor URL: http://www.kernel.org/pub/linux/utils/kernel/kexec/
.SH PARAMETERS

	
.TP
.B -n, --nodename=\fINODE\fP
. 
Name or IP address of node to be fenced. This option is required for the "off" action.
	
.TP
.B -p, --ipport=\fIPORT\fP
. 
IP port number that the \fIfence_kdump\fP agent will use to listen for messages. (Default Value: 7410)
	
.TP
.B -f, --family=\fIFAMILY\fP
. 
IP network family. Force the \fIfence_kdump\fP agent to use a specific family. The value for \fIFAMILY\fP can be "auto", "ipv4", or "ipv6". (Default Value: auto)
	
.TP
.B -o, --action=\fIACTION\fP
. 
Fencing action to perform. The value for \fIACTION\fP can be either "off" or "metadata". (Default Value: off)
	
.TP
.B -t, --timeout=\fITIMEOUT\fP
. 
Number of seconds to wait for message from failed node. If no message is received within \fITIMEOUT\fP seconds, the \fIfence_kdump\fP agent returns failure. (Default Value: 60)
	
.TP
.B -v, --verbose
. 
Print verbose output
	
.TP
.B -V, --version
. 
Print version
	
.TP
.B -h, --help
. 
Print usage

.SH ACTIONS

	
.TP
\fBoff \fP
Power off machine.
	
.TP
\fBmonitor \fP
Check the health of fence device
	
.TP
\fBmetadata \fP
Display the XML metadata describing this resource.

.SH STDIN PARAMETERS

	
.TP
.B nodename
. 
Name or IP address of node to be fenced. This option is required for the "off" action.
	
.TP
.B ipport
. 
IP port number that the \fIfence_kdump\fP agent will use to listen for messages. (Default Value: 7410)
	
.TP
.B family
. 
IP network family. Force the \fIfence_kdump\fP agent to use a specific family. The value for \fIFAMILY\fP can be "auto", "ipv4", or "ipv6". (Default Value: auto)
	
.TP
.B action
. 
Fencing action to perform. The value for \fIACTION\fP can be either "off" or "metadata". (Default Value: off)
	
.TP
.B timeout
. 
Number of seconds to wait for message from failed node. If no message is received within \fITIMEOUT\fP seconds, the \fIfence_kdump\fP agent returns failure. (Default Value: 60)
	
.TP
.B verbose
. 
Print verbose output
	
.TP
.B version
. 
Print version
	
.TP
.B usage
. 
Print usage
