---
- name: mpi.sh
  remote_user: root
  hosts: management,compute
  
  tasks:
   - name: Create & Edit /etc/profile.d/mpi.sh
     copy:
       dest: /etc/profile.d/mpi.sh
       content: | 
         export PATH=/usr/lib64/openmpi/bin:$PATH
         export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH

