
.TH FENCE_AGENT 8 2009-10-20 "fence_ifmib (Fence Agent)"
.SH NAME
fence_ifmib - Fence agent for IF MIB
.SH DESCRIPTION
.P
fence_ifmib is an I/O Fencing agent which can be used with any SNMP IF-MIB capable device. 
.P
It was written with managed ethernet switches in mind, in order to fence iSCSI SAN connections. However, there are many devices that support the IF-MIB interface. The agent uses IF-MIB::ifAdminStatus to control the state of an interface.
.P
fence_ifmib accepts options on the command line as well
as from stdin. Fenced sends parameters through stdin when it execs the
agent. fence_ifmib can be run by itself with command
line options.  This is useful for testing and for turning outlets on or off
from scripts.

Vendor URL: http://www.ietf.org/wg/concluded/ifmib.html
.SH PARAMETERS

	
.TP
.B -o, --action=[action]
. 
Fencing action (Default Value: off)
	
.TP
.B -c, --community=[community]
. 
Set the community string
	
.TP
.B -4, --inet4-only
. 
Forces agent to use IPv4 addresses only
	
.TP
.B -6, --inet6-only
. 
Forces agent to use IPv6 addresses only
	
.TP
.B -a, --ip=[ip]
. 
IP address or hostname of fencing device This parameter is always required.
	
.TP
.B -u, --ipport=[port]
. 
TCP/UDP port to use for connection with device (Default Value: 161)
	
.TP
.B -l, --username=[name]
. 
Login name
	
.TP
.B -p, --password=[password]
. 
Login password or passphrase
	
.TP
.B -S, --password-script=[script]
. 
Script to run to retrieve password
	
.TP
.B -n, --plug=[id]
. 
Physical plug number on device, UUID or identification of machine This parameter is always required.
	
.TP
.B -b, --snmp-auth-prot=[prot]
. 
Set authentication protocol (MD5|SHA)
	
.TP
.B -P, --snmp-priv-passwd=[pass]
. 
Set privacy protocol password
	
.TP
.B -R, --snmp-priv-passwd-script
. 
Script to run to retrieve privacy password
	
.TP
.B -B, --snmp-priv-prot=[prot]
. 
Set privacy protocol (DES|AES)
	
.TP
.B -E, --snmp-sec-level=[level]
. 
Set security level (noAuthNoPriv|authNoPriv|authPriv)
	
.TP
.B -d, --snmp-version=[version]
. 
Specifies SNMP version to use (1|2c|3) (Default Value: 2c)
	
.TP
.B -v, --verbose
. 
Verbose mode
	
.TP
.B -D, --debug-file=[debugfile]
. 
Write debug information to given file
	
.TP
.B -V, --version
. 
Display version information and exit
	
.TP
.B -h, --help
. 
Display help and exit
	
.TP
.B -C, --separator=[char]
. 
Separator for CSV created by 'list' operation (Default Value: ,)
	
.TP
.B --delay=[seconds]
. 
Wait X seconds before fencing is started (Default Value: 0)
	
.TP
.B --login-timeout=[seconds]
. 
Wait X seconds for cmd prompt after login (Default Value: 5)
	
.TP
.B --power-timeout=[seconds]
. 
Test X seconds for status change after ON/OFF (Default Value: 20)
	
.TP
.B --power-wait=[seconds]
. 
Wait X seconds after issuing ON/OFF (Default Value: 0)
	
.TP
.B --shell-timeout=[seconds]
. 
Wait X seconds for cmd prompt after issuing command (Default Value: 3)
	
.TP
.B --retry-on=[attempts]
. 
Count of attempts to retry power on (Default Value: 1)
	
.TP
.B --snmpget-path=[path]
. 
Path to snmpget binary (Default Value: /usr/bin/snmpget)
	
.TP
.B --snmpset-path=[path]
. 
Path to snmpset binary (Default Value: /usr/bin/snmpset)
	
.TP
.B --snmpwalk-path=[path]
. 
Path to snmpwalk binary (Default Value: /usr/bin/snmpwalk)

.SH ACTIONS

	
.TP
\fBon \fP
Power on machine.
	
.TP
\fBoff \fP
Power off machine.
	
.TP
\fBstatus \fP
This returns the status of the plug/virtual machine.
	
.TP
\fBlist \fP
List available plugs with aliases/virtual machines if there is support for more then one device. Returns N/A otherwise.
	
.TP
\fBlist-status \fP
List available plugs with aliases/virtual machines and their power state if it can be obtained without additional commands.
	
.TP
\fBmonitor \fP
Check the health of fence device
	
.TP
\fBmetadata \fP
Display the XML metadata describing this resource.
	
.TP
\fBvalidate-all \fP
Validate if all required parameters are entered.

.SH STDIN PARAMETERS

	
.TP
.B action
. 
Fencing action (Default Value: off)
	
.TP
.B community
. 
Set the community string
	
.TP
.B inet4_only
. 
Forces agent to use IPv4 addresses only
	
.TP
.B inet6_only
. 
Forces agent to use IPv6 addresses only
	
.TP
.B ipaddr
. 
IP address or hostname of fencing device This parameter is always required.
	
.TP
.B ipport
. 
TCP/UDP port to use for connection with device (Default Value: 161)
	
.TP
.B login
. 
Login name
	
.TP
.B passwd
. 
Login password or passphrase
	
.TP
.B passwd_script
. 
Script to run to retrieve password
	
.TP
.B port
. 
Physical plug number on device, UUID or identification of machine This parameter is always required.
	
.TP
.B snmp_auth_prot
. 
Set authentication protocol (MD5|SHA)
	
.TP
.B snmp_priv_passwd
. 
Set privacy protocol password
	
.TP
.B snmp_priv_passwd_script
. 
Script to run to retrieve privacy password
	
.TP
.B snmp_priv_prot
. 
Set privacy protocol (DES|AES)
	
.TP
.B snmp_sec_level
. 
Set security level (noAuthNoPriv|authNoPriv|authPriv)
	
.TP
.B snmp_version
. 
Specifies SNMP version to use (1|2c|3) (Default Value: 2c)
	
.TP
.B verbose
. 
Verbose mode
	
.TP
.B debug
. 
Write debug information to given file
	
.TP
.B version
. 
Display version information and exit
	
.TP
.B help
. 
Display help and exit
	
.TP
.B separator
. 
Separator for CSV created by 'list' operation (Default Value: ,)
	
.TP
.B delay
. 
Wait X seconds before fencing is started (Default Value: 0)
	
.TP
.B login_timeout
. 
Wait X seconds for cmd prompt after login (Default Value: 5)
	
.TP
.B power_timeout
. 
Test X seconds for status change after ON/OFF (Default Value: 20)
	
.TP
.B power_wait
. 
Wait X seconds after issuing ON/OFF (Default Value: 0)
	
.TP
.B shell_timeout
. 
Wait X seconds for cmd prompt after issuing command (Default Value: 3)
	
.TP
.B retry_on
. 
Count of attempts to retry power on (Default Value: 1)
	
.TP
.B snmpget_path
. 
Path to snmpget binary (Default Value: /usr/bin/snmpget)
	
.TP
.B snmpset_path
. 
Path to snmpset binary (Default Value: /usr/bin/snmpset)
	
.TP
.B snmpwalk_path
. 
Path to snmpwalk binary (Default Value: /usr/bin/snmpwalk)
