
.TH FENCE_AGENT 8 2009-10-20 "fence_dummy (Fence Agent)"
.SH NAME
fence_dummy - Dummy fence agent
.SH DESCRIPTION
.P
fence_dummy
.P
fence_dummy accepts options on the command line as well
as from stdin. Fenced sends parameters through stdin when it execs the
agent. fence_dummy can be run by itself with command
line options.  This is useful for testing and for turning outlets on or off
from scripts.

Vendor URL: http://www.example.com
.SH PARAMETERS

	
.TP
.B -o, --action=[action]
. 
Fencing action (Default Value: reboot)
	
.TP
.B --random_sleep_range=[seconds]
. 
Issue a sleep between 1 and X seconds. Used for testing.
	
.TP
.B --status-file=[file]
. 
File with status (Default Value: /tmp/fence_dummy.status)
	
.TP
.B --type=[type]
. 
Type of the dummy fence agent (Default Value: file)
	
.TP
.B -v, --verbose
. 
Verbose mode
	
.TP
.B -D, --debug-file=[debugfile]
. 
Write debug information to given file
	
.TP
.B -V, --version
. 
Display version information and exit
	
.TP
.B -h, --help
. 
Display help and exit
	
.TP
.B --delay=[seconds]
. 
Wait X seconds before fencing is started (Default Value: 0)
	
.TP
.B --login-timeout=[seconds]
. 
Wait X seconds for cmd prompt after login (Default Value: 5)
	
.TP
.B --power-timeout=[seconds]
. 
Test X seconds for status change after ON/OFF (Default Value: 20)
	
.TP
.B --power-wait=[seconds]
. 
Wait X seconds after issuing ON/OFF (Default Value: 0)
	
.TP
.B --shell-timeout=[seconds]
. 
Wait X seconds for cmd prompt after issuing command (Default Value: 3)
	
.TP
.B --retry-on=[attempts]
. 
Count of attempts to retry power on (Default Value: 1)

.SH ACTIONS

	
.TP
\fBon \fP
Power on machine.
	
.TP
\fBoff \fP
Power off machine.
	
.TP
\fBreboot \fP
Reboot machine.
	
.TP
\fBstatus \fP
This returns the status of the plug/virtual machine.
	
.TP
\fBmonitor \fP
Check the health of fence device
	
.TP
\fBmetadata \fP
Display the XML metadata describing this resource.
	
.TP
\fBvalidate-all \fP
Validate if all required parameters are entered.

.SH STDIN PARAMETERS

	
.TP
.B action
. 
Fencing action (Default Value: reboot)
	
.TP
.B random_sleep_range
. 
Issue a sleep between 1 and X seconds. Used for testing.
	
.TP
.B status_file
. 
File with status (Default Value: /tmp/fence_dummy.status)
	
.TP
.B type
. 
Type of the dummy fence agent (Default Value: file)
	
.TP
.B verbose
. 
Verbose mode
	
.TP
.B debug
. 
Write debug information to given file
	
.TP
.B version
. 
Display version information and exit
	
.TP
.B help
. 
Display help and exit
	
.TP
.B delay
. 
Wait X seconds before fencing is started (Default Value: 0)
	
.TP
.B login_timeout
. 
Wait X seconds for cmd prompt after login (Default Value: 5)
	
.TP
.B power_timeout
. 
Test X seconds for status change after ON/OFF (Default Value: 20)
	
.TP
.B power_wait
. 
Wait X seconds after issuing ON/OFF (Default Value: 0)
	
.TP
.B shell_timeout
. 
Wait X seconds for cmd prompt after issuing command (Default Value: 3)
	
.TP
.B retry_on
. 
Count of attempts to retry power on (Default Value: 1)
